Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rentalmandu.Areas.Identity.Data;
using Rentalmandu.Models;
using Microsoft.Extensions.Hosting;

namespace Rentalmandu.Controllers
{
    public class CarController : Controller
    {
        private readonly HajurKoCarRentalDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public CarController(HajurKoCarRentalDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Car
        public async Task<IActionResult> Index()
        {
              return _context.CarInfo != null ? 
                          View(await  _context.CarInfo.ToListAsync()) :
                          Problem("Entity set 'HajurKoCarRentalDbContext.CarInfo'  is null.");
        }

        // GET: Car/CarAvailable
        public async Task<IActionResult> CarAvailable()
        {
            var availableCars = await _context.CarInfo.Where(c => c.IsAvailable).ToListAsync();
            return View("Index", availableCars);
        }

        // GET: Car/CarOnRent
        public async Task<IActionResult> CarOnRent()
        {
            var carsOnRent = await _context.CarInfo.Where(c => !c.IsAvailable).ToListAsync();
            return View("Index", carsOnRent);
        }

        // GET: Car/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CarInfo == null)
            {
                return NotFound();
            }

            var carInfo = await _context.CarInfo
                .FirstOrDefaultAsync(m => m.id == id);
            if (carInfo == null)
            {
                return NotFound();
            }

            return View(carInfo);
        }

        // GET: Car/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Car/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,CarImage,CarName,Brand,Model,PricePerDay,IsAvailable")] CarInfo carInfo)
        {
            if (ModelState.IsValid)
            {
                var file = HttpContext.Request.Form.Files.FirstOrDefault();

                // Check if a file is uploaded
                if (file != null && file.Length > 0)
                {
                    // Generate a unique file name
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);

                    // Set the image file name property
                    carInfo.CarImage = fileName;

                    // Set the file path to save in wwwroot/images folder
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", fileName);

                    // Save the image file to the specified path
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }

                _context.Add(carInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(carInfo);
        }



        // GET: Car/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CarInfo == null)
            {
                return NotFound();
            }

            var carInfo = await _context.CarInfo.FindAsync(id);
            if (carInfo == null)
            {
                return NotFound();
            }
            return View(carInfo);
        }

        // POST: Car/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,CarImage,CarName,Brand,Model,PricePerDay,IsAvailable")] CarInfo carInfo, IFormFile carImageFile)
        {
            if (id != carInfo.id)
            {
                return NotFound();
            }

            
                try
                {
                    var existingCar = await _context.CarInfo.FindAsync(id);

                    // Delete the previous image file
                    if (carImageFile != null && !string.IsNullOrEmpty(existingCar.CarImage))
                    {
                        var existingImagePath = Path.Combine(_hostingEnvironment.WebRootPath, "images", existingCar.CarImage);
                        if (System.IO.File.Exists(existingImagePath))
                        {
                            System.IO.File.Delete(existingImagePath);
                        }
                    }

                    // Update the car information
                    _context.Entry(existingCar).CurrentValues.SetValues(carInfo);

                    // Check if a new image file is uploaded
                    if (carImageFile != null)
                    {
                        // Generate a unique file name for the new image
                        var uniqueFileName = GetUniqueFileName(carImageFile.FileName);

                        // Save the new image file to the wwwroot/images directory
                        var imagePath = Path.Combine(_hostingEnvironment.WebRootPath, "images", uniqueFileName);
                        using (var fileStream = new FileStream(imagePath, FileMode.Create))
                        {
                            await carImageFile.CopyToAsync(fileStream);
                        }

                        // Update the car's image file name
                        existingCar.CarImage = uniqueFileName;
                    }

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarInfoExists(carInfo.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            

            
        }


        // Generate a unique file name for the image
        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                + "_"
                + Guid.NewGuid().ToString().Substring(0, 4)
                + Path.GetExtension(fileName);
        }


        // GET: Car/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CarInfo == null)
            {
                return NotFound();
            }

            var carInfo = await _context.CarInfo
                .FirstOrDefaultAsync(m => m.id == id);
            if (carInfo == null)
            {
                return NotFound();
            }

            return View(carInfo);
        }

        // POST: Car/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CarInfo == null)
            {
                return Problem("Entity set 'HajurKoCarRentalDbContext.CarInfo'  is null.");
            }
            var carInfo = await _context.CarInfo.FindAsync(id);
            if (carInfo != null)
            {
                _context.CarInfo.Remove(carInfo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarInfoExists(int id)
        {
          return (_context.CarInfo?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rentalmandu.Areas.Identity.Data;
using Rentalmandu.Models;

namespace Rentalmandu.Controllers
{
    public class OfferController : Controller
    {
        private readonly HajurKoCarRentalDbContext _context;

        public OfferController(HajurKoCarRentalDbContext context)
        {
            _context = context;
        }

        // GET: Offer
        public async Task<IActionResult> Index()
        {
            var hajurKoCarRentalDbContext = _context.Offer.Include(o => o.CarInfo);
            return View(await hajurKoCarRentalDbContext.ToListAsync());
        }

        // GET: Offer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .Include(o => o.CarInfo)
                .FirstOrDefaultAsync(m => m.id == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // GET: Offer/Create
        public IActionResult Create()
        {
            ViewData["CarID"] = new SelectList(_context.CarInfo, "id", "CarName");
            return View();
        }

        // POST: Offer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Title,Description,CarID,Discount,StartDate,EndDate")] Offer offer)
        {
            
                _context.Add(offer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            
        }

        // GET: Offer/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer.FindAsync(id);
            if (offer == null)
            {
                return NotFound();
            }
            ViewData["CarID"] = new SelectList(_context.CarInfo, "id", "CarName", offer.CarID);
            return View(offer);
        }

        // POST: Offer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Title,Description,CarID,Discount,StartDate,EndDate")] Offer offer)
        {
            if (id != offer.id)
            {
                return NotFound();
            }

            
                try
                {
                    _context.Update(offer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfferExists(offer.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            
           
        }

        // GET: Offer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .Include(o => o.CarInfo)
                .FirstOrDefaultAsync(m => m.id == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // POST: Offer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Offer == null)
            {
                return Problem("Entity set 'HajurKoCarRentalDbContext.Offer'  is null.");
            }
            var offer = await _context.Offer.FindAsync(id);
            if (offer != null)
            {
                _context.Offer.Remove(offer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OfferExists(int id)
        {
          return (_context.Offer?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Rentalmandu.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {
            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                await _roleManager.CreateAsync(new IdentityRole(model.Name));
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(IdentityRole model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                return NotFound();
            }

            role.Name = model.Name;
            await _roleManager.UpdateAsync(role);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            await _roleManager.DeleteAsync(role);

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentalMandu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HajurKoCarRental.styles.css" asp-append-version="true" />
</head>
<style>
    /* Add hover effect to element */
    .my-element:hover {
        transform: scale(1.1);
        transition: transform 0.2s ease-in-out; /* Add smooth transition */
        text-decoration: line-through;
        box-shadow: 5px 0px 10px black /* Add box shadow */
    }

</style>
<body>
    <header style="background-color: #7289DA">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid" style="background-color: #7289DA">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RentalMandu</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark my-element" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>



                        @if (User.IsInRole("admin") || User.IsInRole("staff"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark my-element" asp-area="" asp-controller="ManageRental" asp-action="Index">Manage Rental Request</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark my-element" asp-area="" asp-controller="Car" asp-action="Index">Manage Car</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark my-element" asp-area="" asp-controller="Staff" asp-action="Index">Manage Staff</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark my-element" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark my-element" asp-area="" asp-controller="rental" asp-action="allusers">Users History</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark my-element" asp-area="" asp-controller="rental" asp-action="allrentals">Sales</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark my-element" asp-area="" asp-controller="rental" asp-action="activeusers">Active Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark my-element" asp-area="" asp-controller="rental" asp-action="inactiveusers">Inactive Users</a>
                            </li>
                        }

                        @if (User.IsInRole("admin"))
                        {


                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark my-element" asp-area="" asp-controller="Rental" asp-action="RentalHistory">Rental History</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark my-element" asp-area="" asp-controller="CarDamage" asp-action="Index">Car Damage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark my-element" asp-area="" asp-controller="Offer" asp-action="Index">Offer</a>
                        </li>
                       
                       


                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-secondary">
        <div class="container" style="color: white">
            &copy; 2023 - RentalMandu - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color: white">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>